name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "mayor:"
        minor_pattern: "feat:"
      id: version
    - name: Login in Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "$NEW_VERSION"
        docker login -u $DOCKER_USER -p $DOCKER_PASS                
    # - name: Build Docker Image
    #   run: |
    #     docker build -t edwinespi18/docker-graphql:0.0.3 .
    # - name: Push Docker Image
    #   run: |
    #     docker push edwinespi18/docker-graphql:0.0.3
    # - name: Update tag latest Docker Image
    #   run: |
    #     docker build -t edwinespi18/docker-graphql .
    #     docker push edwinespi18/docker-graphql
